window.CARD_DATA = window.CARD_DATA || {};

window.CARD_DATA.explora = {
  id: "explora",
  name: "Explora Banamex",
  segment: "platinum",
  color: "#706F6F",
  image: "img/explora.png",
  income: "75 MIL",
  cat: "78.5% sin IVA",
  rate: "56.48%",
  admin: "$227.08 sin IVA",
  additional: "$113.33 sin IVA",
  validity:
    "<strong>CAT PROMEDIO 78.5% sin IVA Informativo.</strong> Vigencia de la oferta: <strong>27 de Julio del 2026 al 27 de Enero del 2027.</strong> Tasa de interés anual promedio ponderada de <strong>56.48% tasa variable</strong> y una comisión por <strong>administración mensual de $227.08 sin IVA</strong>, ¿de acuerdo?",
  script:
    "Según su perfil, el producto que le estaría recomendando es la TDC EXPLORA, la cual ya es una categoría PLATINUM que le estará brindando beneficios exclusivos de esta categoría, como 10 accesos gratuitos anuales en aeropuertos de la Ciudad de México (T1 y T2), Guadalajara y Monterrey, para brindarle mayor comodidad en sus viajes, incluso meses sin intereses en múltiples espacios, para ello, yo lo apoyaré con su solicitud.\n\nEsta tarjeta EXPLORA le genera una administración mensual de $227.08 sin IVA, la cual podrá exentar con una compra mínima de 300 pesos al mes en el primer año.\n\nCAT PROMEDIO 78.5% sin IVA. Tasa de interés anual promedio ponderada de 56.48% tasa variable y una comisión por administración mensual de $227.08 sin IVA, ¿de acuerdo?",
  bonification: [
    "<strong>Activar la TDC Física y Digital asi como NetKey</strong>",
    "<strong><strong>Realizar una compra sin monto mínimo con la tarjeta digital (EL PRIMER MES).</strong></strong>",
    "<strong>A partir del segundo mes y hasta el mes 12 deberá mantener un consumo mínimo en compras de $300 con la tarjeta de crédito física o digital, para exentar la administración mensual.</strong>",
  ],
  benefits: [
    "<strong>1.15 PUNTOS MOMENTOS BANAMEX:</strong> por cada dólar gastado ó su equivalente en pesos (Los puntos tienen vigencia de 3 años). ¡Tus Tarjetas adicionales también generan puntos por compras!",
    "<strong>2X1 EN BOLETOS DE AVIÓN:</strong> Viaja a playas nacionales con un certificado 2x1 en boletos de avión, puedes obtenerlo como bienvenida durante los primeros 3 meses con tu tarjeta o en cada aniversario. La condición para obtener el de bienvenida es acumular <strong><strong>1,300 puntos en los primeros 3 meses</strong></strong>, y para obtener el de aniversario, debe acumular <strong>mínimo 10,000 PUNTOS</strong>.",
    "<strong>10 accesos GRATIS en las SALAS BEYOND</strong> para usted y 1 acompañante y… <strong>4 accesos a Salas Lounge Key</strong> en mas de 1200 salas VIP alrededor del mundo al año <strong>(Los accesos fuera de estas cortesias tienen un costo de $32 dolares por persona).</strong>",
    "<strong>MASTERCARD CONCIERGE</strong> asistente personal 24/7, Atención personalizada en todo el mundo para realizar reservas de restaurantes, coordinación de eventos especiales, entre otras.",
    "<strong><strong>Elite Valet MasterCard:</strong></strong> En el Aeropuerto Internacional de la Ciudad de México encontraras el servicio de Elite Valet MC. Con tu Tarjeta Citibanamex Platinum obtén 50% de descuento. El servicio es por hasta 5 días naturales, 2 entradas por mes.",
    "<strong>Premium Weekend:</strong> Promociones excusivas con marcas de lujo, asi como experiencias únicas.",
    "<strong>SEGUROS MASTERCARD:</strong> Recibe asistencias de viaje, equipaje, autos y toda la protección que necesitas.",
    "<strong><strong>Preventas exclusivas</strong></strong>: Compra tus boletos antes que nadie, elige el mejor lugar para tus eventos culturales, deportivos y lo mejor de los espectáculos en México.",
  ],
  travelBenefitsTable: {
    destinations: {
      us: [
        "Albuquerque",
        "Atlanta",
        "Baltimore",
        "Boston",
        "Chicago",
        "Dallas",
        "Denver",
        "Houston",
        "Indianápolis",
        "Las Vegas",
        "Los Ángeles",
        "Miami",
        "Newark",
        "Nueva York",
        "Orlando",
        "Phoenix",
        "Salt Lake City",
        "San Antonio",
        "San Diego",
        "San Francisco",
        "Seattle",
        "Washington",
      ],
      national: [
        "Acapulco",
        "Cabo San Lucas",
        "Cancún",
        "Ciudad de México",
        "Hermosillo",
        "Guadalajara",
        "Mazatlán",
        "Monterrey",
        "Puerto Vallarta",
        "Oaxaca",
        "Tampico",
        "Tijuana",
        "Veracruz",
      ],
    },
    certificates: [
      {
        title: "Bienvenida(1)",
        text: "Acumulando un mínimo de 1,300 puntos durante los primeros 3 meses con tu Tarjeta de Crédito Explora Banamex, a partir de que se origina la cuenta.",
        icon: "card",
      },
      {
        title: "Aniversario(1)",
        text: "Acumulando un mínimo de 10,000 Puntos cada año, entre un aniversario y otro, sin importar si redimes antes tus puntos.",
        icon: "cake",
      },
    ],
  },
  extraTitle: "Destinos y certificado 2x1 (beneficios de viaje)",
};
